### PR TITLE
Zuul migration

### PR DESCRIPTION
**Pull request by rgarrigue**

### CODE REVIEW

**Comment by rgarrigue** [comment]
recheck

**Comment by ghost** [comment]
Build succeeded.

- [tox-linters ](https://zuul.wazo.community/logs/8/8/f4f67a3d622f8bcf045878020ac5a6e527e6687c/check/tox-linters/22a01b1/) : SUCCESS in 9m 59s
- [wazo-tox-py37 ](https://zuul.wazo.community/logs/8/8/f4f67a3d622f8bcf045878020ac5a6e527e6687c/check/wazo-tox-py37/f455a80/) : SUCCESS in 10m 03s
- [debian-packaging ](https://zuul.wazo.community/logs/8/8/f4f67a3d622f8bcf045878020ac5a6e527e6687c/check/debian-packaging/a5f2fb8/) : SUCCESS in 9m 26s

**Comment by rgarrigue** [comment]
I guess it's missing a Depends-On ? Good enough anyway

```
2021-04-08 10:34:32.183603 | TASK [wazo-tox : Install any sibling python packages]
2021-04-08 10:34:34.839264 | pod-debian-10 | ERROR
2021-04-08 10:34:34.839648 | pod-debian-10 | {
2021-04-08 10:34:34.839724 | pod-debian-10 |   "log": "Processing siblings for b'wazo-router-calld' from src/github.com/wazo-platform/wazo-router-calld\na bytes-like object is required, not 'str'\nTraceback (most recent call last):\n  File \"/tmp/ansible_tox_install_sibling_packages_payload_ox47ahr8/ansible_tox_install_sibling_packages_payload.zip/ansible/modules/tox_install_sibling_packages.py\", line 227, in main\n  File \"/tmp/ansible_tox_install_sibling_packages_payload_ox47ahr8/ansible_tox_install_sibling_packages_payload.zip/ansible/modules/tox_install_sibling_packages.py\", line 121, in get_installed_packages\nTypeError: a bytes-like object is required, not 'str'\n",
2021-04-08 10:34:34.839785 | pod-debian-10 |   "msg": "a bytes-like object is required, not 'str'"
2021-04-08 10:34:34.839836 | pod-debian-10 | }
```

**Comment by sduthil** [comment]
recheck

**Pull request closed without merging**
